baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Asmaa Abushalhoub"
theme = "hugo-coder"

[params]
  author = "Asmaa Abushalhoub"
  info = ["Communication Researcher", "Language tutor", "Digital Nomad"]
  description = "Asmaa Abushalhoub - Communication Researcher, Language Tutor, and Digital Nomad."
customCSS = ["css/custom.css"]